# Dockerfile > Docker Image > Run Docker Containers

FROM alpine:latest
LABEL org.opencontainers.image.source=https://github.com/philippesollaud/exercise-publish-package
CMD [ "echo", "hello from packages" ]
