name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker build . -f sample-packages/docker/Dockerfile --tag ghcr.io/philippesollaud/hello-world:latest
        docker run ghcr.io/philippesollaud/hello-world:latest
        docker push ghcr.io/philippesollaud/hello-world:latest
